apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: team-2
  namespace: default
spec:
  interval: 1m
  releaseName: team-2
  chart:
    spec:
      chart: charts/team
      sourceRef:
        kind: GitRepository
        name: test
        namespace: default
      interval: 1m
  values:
    teamName: team-2
