apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: {{ .Values.teamName }}
  namespace: default
spec:
  interval: 5m
  path: "/{{ .Values.teamName }}"
  prune: true
  sourceRef:
    kind: GitRepository
    name: test
  timeout: 2m